import { useEffect, useState } from 'react';
const labels: Record<string,string> = {backup:'公開バックアップ',deface:'管理APIで表示変更'};
interface Site { id:string; definition:{name:string}; themes:string[]; difficulty:string; missions?:Record<string,string>; hints?:{theme:string;title:string;steps:{text:string;command?:string}[]}[]; cleared:boolean; solved:string[]; checks:Check[]; }
interface Check {theme:string;vulnerable:unknown;secure:unknown;blocked:boolean}
interface Props {onPreview:(mode:'vulnerable'|'secure',id:string)=>void;onInsertCommand:(text:string)=>void}
export function MockSitePanel({onPreview,onInsertCommand}:Props){
 const [screenshot,setScreenshot]=useState('');const [imageName,setImageName]=useState('');const [imageLoading,setImageLoading]=useState(false);
 const [url,setUrl]=useState('https://example.com/');const [site,setSite]=useState<Site|null>(null);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [answer,setAnswer]=useState('');const [clear,setClear]=useState(false);const [checks,setChecks]=useState<Check[]>([]);const [mode,setMode]=useState<'vulnerable'|'secure'>('vulnerable');
 const call=async(action:string,body:unknown)=>{const r=await fetch('/api/mock-site/'+action,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error??'処理に失敗しました');return b;};
 useEffect(()=>{let active=true;void fetch('/api/mock-site').then(r=>r.json()).then(b=>{if(active&&b.site){setSite(b.site);setClear(b.site.cleared);setChecks(b.site.checks);onPreview('vulnerable',b.site.id);}}).catch(()=>{});return()=>{active=false;};},[]);
 useEffect(()=>{if(!site)return;const timer=window.setInterval(()=>{void fetch('/api/mock-site').then(r=>r.json()).then(b=>{if(b.site){if(b.site.id!==site.id){setClear(false);setAnswer('');setChecks(b.site.checks);onPreview(mode,b.site.id);}setClear(b.site.cleared);setSite(b.site);}}).catch(()=>{});},5000);return()=>window.clearInterval(timer);},[site?.id,mode]);
 const run=async(name:string,fn:()=>Promise<void>)=>{setBusy(name);setError('');try{await fn();}catch(e){setError(name+'：'+(e instanceof Error?e.message:'処理に失敗しました')+(name.includes('AI生成')&&site?' 以前の模擬サイトを表示しています。':''));}finally{setBusy('');}};
 const attach=async(file?:File)=>{setError('');setScreenshot('');setImageName('');if(!file)return;setImageLoading(true);try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw new Error('10MB以下のPNG・JPEG・WebPを選んでください。');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d');if(!context){bitmap.close();throw new Error('画像を読み込めません。');}context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/jpeg',.8);if(data.length>2100000)throw new Error('画像が大きすぎます。小さなスクショを選んでください。');setScreenshot(data);setImageName(file.name);}catch(e){setError(e instanceof Error?e.message:'画像を読み込めません。');}finally{setImageLoading(false);}};
 const flagCommand=`curl -sS --max-time 10 -H "X-TerminalBox-Session: $TERMINALBOX_SESSION_ID" http://mocksite:3200/vulnerable/api/flag; printf '\\n'`;

 return <section className="panel mock-site-panel" id="mock-site-panel" role="tabpanel" aria-labelledby="mock-site-tab"><div className="panel-heading"><h2>模擬サイト</h2></div><div className="mock-site-content">
 <p>実在するWebサイトを参考に、セキュリティ学習用の模擬サイトをAIが生成します。</p>
 <form onSubmit={e=>{e.preventDefault();void run('① URL解析 → ② AI生成',async()=>{const b=await call('generate',{url,screenshot});setSite(b.site);setChecks([]);setClear(false);setMode('vulnerable');onPreview('vulnerable',b.site.id);});}}>
 <label>URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} required maxLength={2048}/></label>
 <label>スクショ（任意）<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!!busy||imageLoading} onChange={e=>void attach(e.target.files?.[0])}/></label>
 {imageLoading&&<p role="status">画像を準備しています…</p>}{screenshot&&<div className="mock-image-preview"><img src={screenshot} alt="添付するスクショ"/><p>{imageName}</p><button type="button" onClick={()=>{setScreenshot('');setImageName('');}}>画像を取り消す</button></div>}
 <p>見た目を参考にしたい画面を添付してください。画像は縮小してAIへ送信します。個人情報が写っていない画像をご利用ください。</p>
 <button className="mock-primary" disabled={!!busy||imageLoading}>模擬サイトを生成</button></form>
 <p>※ 入力したWebサイト自体への攻撃・脆弱性診断は行いません。</p><p>URLの文章と任意のスクショから、用途・配色・配置を参考に架空の教材を作成します。内部機能や弱点は教材用です。公開IPv4があるサイトに対応し、安全性を確認しながら最大3回の転送をたどります。IPv6のみのサイトや取得制限のあるサイトは解析できません。URLを取得できない場合は、添付画像から生成します。生成は1セッション3回までです。</p>
 {busy&&<p role="status">{busy}…</p>}{error&&<p role="alert">{error}</p>}
 {site&&<><h3>③ MISSION：管理APIで表示を変更する</h3><p>下の4つのコマンドを上から順にコピーしてTerminalへ貼り付け、Enterを押してください。管理キーの書き写しやコマンドの編集は不要です。</p>
 <p>対象はこの教材だけです：<code>http://mocksite:3200/vulnerable/</code></p>
 <p>進捗：{site.solved.includes('backup')?'✓':'□'} 管理キー取得　{site.solved.includes('deface')?'✓':'□'} 表示変更 </p>
 <h3>④ 調査</h3>
 {site.hints?.map(h=><article key={h.theme}><h3>{h.title}</h3>{h.steps.map((step,i)=><div key={i}><p>{step.text}</p>{step.command&&<><code className="mock-hint-command">{step.command}</code><button onClick={()=>void navigator.clipboard.writeText(step.command!).catch(()=>setError('コピーできませんでした。「Terminalへ」を使ってください。'))}>コピー</button><button onClick={()=>onInsertCommand(step.command!)}>Terminalへ</button></>}</div>)}</article>)}
 <p>「コピー」はクリップボードへコピー、「Terminalへ」はターミナルへ貼り付けます。貼り付けた後にEnterを押してください。手順3の後に模擬サイト表示の「再読み込み」を押すと、変更したタイトルが見えます。HPを復元した場合は手順1からやり直してください。</p>
 <div className="lesson-title-row"><h3>⑤ Flagを回答</h3><span className={`lesson-clear-badge ${clear?'cleared':''}`} role="status">{clear?'クリア':'未クリア'}</span></div><button disabled={!!busy||!clear} onClick={()=>void run('クリア解除',async()=>{await call('unclear',{});setClear(false);setAnswer('');})}>クリア解除</button><button disabled={!!busy} onClick={()=>void run('Flag取得',async()=>{const b=await fetch('/api/mock-site').then(r=>r.json());if(!b.site)throw new Error('模擬サイトを先に生成してください。');setSite(b.site);if(!b.site.solved.includes('backup')||!b.site.solved.includes('deface'))throw new Error('手順2と3を実行してからFlagを取得してください。');onInsertCommand('\u0015'+flagCommand+'\r');})}>Flag取得をTerminalで実行</button>
 <form onSubmit={e=>{e.preventDefault();void run('Flag判定',async()=>{const b=await call('check',{answer});setClear(b.cleared);if(!b.correct)throw new Error('手順を完了し、表示されたTBX{…}をそのまま貼り付けてください。');});}}><input aria-label="Flag回答" placeholder="TBX{…} を貼り付け" value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={200}/><button disabled={!!busy}>回答</button></form>
 <h3>⑥ Secure版と比較</h3>{(['vulnerable','secure'] as const).map(m=><button key={m} onClick={()=>{setMode(m);onPreview(m,site.id);}}>{m==='secure'?'Secure版':'脆弱版'}を表示</button>)}<button disabled={!!busy} onClick={()=>void run('同じ入力で比較',async()=>setChecks((await call('compare',{})).checks))}>同じ検証入力で比較</button><p>比較は演習エンジンの同じ処理に入力し、達成状態を変更せずに実施します。Secureは選択した演習への対策版であり、あらゆる安全性を保証するものではありません。</p>{checks.map(c=><article key={c.theme}><strong>{labels[c.theme]}：{c.blocked?'防御確認':'要確認'}</strong><pre>脆弱版：{JSON.stringify(c.vulnerable,null,2)}{'\n'}Secure版：{JSON.stringify(c.secure,null,2)}</pre></article>)}</>}
 </div></section>;
}
